### PR TITLE
#775 - Explicitly resolve deferred values

### PR DESCRIPTION
**Pull request by fetzerms**
From Puppet Agent v8 onwards, a deferred value needs to be explicitly resolved.

## Summary
This adds explicitly resolving of deferred values. See #775 
If that fix is suitable (works for me), I'll be happy to add Spec and acceptance tests for deferred values.

## Additional Context
I don't know of the root cause. Seems Puppet Agent v8 is doing things differently than <=v7

## Related Issues (if any)
#775 

## Checklist
- [ ] 🟢 Spec tests.
- [x] 🟢 Acceptance tests.
- [x] Manually verified. (For example `puppet apply`)

### CODE REVIEW

**Review by smortex — APPROVED** [review]
LGTM!

**Comment by smortex** [comment]
Failed unit tests seems transient. Closing and re-opening to trigger a new run.

**Comment by fetzerms** [comment]
@smortex - As the build is green now, do we think we can merge this?

**Comment by smortex** [comment]
That seems good to me. There is no "policy" AFAIC for external contributors like me and other folks that where added as reviewers, but I would prefer to see a review/approval by someone from @puppetlabs since they own the project.

**Review by joshcooper — APPROVED** [review]
I filed a puppet bug about this, the intention was not to leak deferred values into custom type/providers. But this seems like an ok workaround.

**Review by bastelfreak — APPROVED** [review]

**Pull request merged**
