### PR TITLE
Removing travis badge

### PR DESCRIPTION
**Pull request by nibalizer**

### CODE REVIEW

**Comment by mhaskel** [comment]
thanks @nibalizer

**Comment by ghoneycutt** [comment]
Why remove the travis badge?

**Comment by nibalizer** [comment]
See #puppet-dev this afternoon

**Comment by igalic** [comment]
@nibalizer it'd still be nice to put a short summary for people who weren't involved in the discussion. ideally in the commit message, but here will do just fine

**Pull request merged**
