### PR TITLE
(MODULES-1700) Fix broken backup

### PR DESCRIPTION
**Pull request by jhoblitt**

### CODE REVIEW

**Comment by jhoblitt** [comment]
This is #359 rebased on the current master with an additional commit that explicitly sets the backup parameter on all file resources and further removes any usage of resource defaults.  It would be great if someone who actively uses the static compiler could try this in a test environment.

/cc @j-vizcaino @bmjen @mhaskel

**Comment by bmjen** [comment]
@jhoblitt This PR should be into 1.2.x no?

**Comment by jhoblitt** [comment]
@bmjen no - all changes go to master.  The forge team will handle release branches.

**Comment by bmjen** [comment]
@jhoblitt sorry, I haven't had a chance to review this yet. I thought this was a revert/fix for #359, which was merged into 1.2.x, thus 1.2.x would need to be patched/fixed before we did a mergeback to master.

**Comment by jhoblitt** [comment]
@bmjen #359 was reverted from 1.2.x.  Everything prior to the merge/revert of #359 has been merged into master.

**Comment by bmjen** [comment]
@jhoblitt I will merge this PR to fix the duplicate fragment issue, however we are going to implement a different fix for MODULES-1700 that should work both usecases (regular and static compilation)

**Pull request merged**
