### PR TITLE
(╯°□°)╯︵┻━┻ the 2.0.x rewrite

### PR DESCRIPTION
**Pull request by bmjen**

### CODE REVIEW

**Comment by lollipopman** [comment]
@bmjen I have a fair bit of context on this issue from encountering the bug myself, as well as testing @hunner's pull request, but for others and for the historical record I think a more descriptive message than this one would have been helpful.

**Comment by bennycornelissen** [comment]
A more descriptive message would be helpful indeed. I'm just seeing this PR as my R10K deployment started failing a few minutes ago 😉

**Comment by mhaskel** [comment]
sorry @lollipopman @bennycornelissen, should've checked that before merging. @bmjen will add more in the comments here at least.

**Pull request merged**
