### PR TITLE
set group of fragments to gid

### PR DESCRIPTION
**Pull request by duritong**
gid has now been part of facter for a long time, it is safe to use
it now.

### CODE REVIEW

**Comment by sathieu** [comment]
any new on this PR?

**Comment by jhoblitt** [comment]
I'm hesitant to assume `$::gid` is universally present but setting an internal constraint on `$::facterversion` seems like a lot of complexity for little net functionality.

@hunner Is there a [planned] way to place a dependency on the facter version via `metadata.json`?

Also, since this PR modifies the public API the README documentation would need to be updated.

**Comment by duritong** [comment]
I had a quick look at the README and so far only API deprecations are documented. This change doesn't deprecate anything it adds a new feature. If you tell me where you like to have changes like this document, I can adapt the PR

**Comment by duritong** [comment]
btw: I rebased it into current master

**Comment by mhaskel** [comment]
Hi @duritong,

Thanks for the contribution! It looks like there aren't actually any docs updates needed since you didn't add any parameters that are exposed through a class/defined type.

This fact was added in facter 2.2, so I think we still need to account for it not being present. Could you wrap the new parameter in something like [this](https://github.com/puppetlabs/puppetlabs-concat/blob/master/manifests/init.pp#L202) and explicitly set `$fragment_group` to `undef` if the fact isn't defined?

Thanks!

**Comment by duritong** [comment]
I updated my pull request as discussed

**Comment by mhaskel** [comment]
great, thanks @duritong !

**Comment by jhoblitt** [comment]
uh, this PR changes the public API...

**Comment by duritong** [comment]
@jhoblitt I specifically asked you where to document it and later @mhaskel agreed with me that we didn't add a new parameter.

So if you want me to document that change, you must be more specific and verbose of what should be added. Thanks.

**Comment by mhaskel** [comment]
@jhoblitt this only adds in-class variables, no new parameters.

**Comment by jhoblitt** [comment]
@mhaskel  `concat::fragment::fraggroup` is not a parameter?

**Comment by jhoblitt** [comment]
Ignore me -- my case of the flu has been talking.  This is :+1:

**Comment by mhaskel** [comment]
feel better!

**Comment by sodabrew** [comment]
Hi, this means I need Facter 2.0 or higher on all nodes. What's the purpose of this functionality in the first place? I never want the ownership of the concatfragments.sh to be anything other than root.

**Comment by duritong** [comment]
It just brings everything in line. Owner and mode are already managed, so why not group?

Additionally, if you don't manage the group, group ownership is in kind of a limbo state, as it's not sure that the group will really be root. Especially, if you copy fragments from a source.
And as you might see from the deprecation messages, you can't actually set the owner, group nor mode it has no effect: https://github.com/puppetlabs/puppetlabs-concat/blob/0aa6c635c13e5978f38000e2f6d64b4796a02b4a/manifests/fragment.pp#L48-L56

And last but not least: We can't hardcode it to root, because this would make the concat module unusable if you run puppet as a unprivileged user. There are tons of valid use cases for that and there is no reason that the concat module requires root to be used.

**Comment by sodabrew** [comment]
Thanks for the explanation. Looks like it's doing the right thing for me since #280 as a fallback for not having the gid fact on my older nodes.

**Pull request merged**
